name: "CI Action"

on:
    push:
        branches:
            - "master"
    pull_request:
        branches:
            - "master"

jobs:
    testing:
        name: "Run Pint, PHPUnit and PHPStan"
        runs-on: ubuntu-22.04

        steps:
            -   name: "Setup PHP"
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "8.2"
                    tools: composer:v2
                    ini-values: "memory_limit=-1"
                env:
                    fail-fast: true

            -   name: "Checkout Project"
                uses: actions/checkout@v3

            -   name: "Install Dependencies"
                run: composer install

            -   name: "Setup environment"
                run: cp .env.example .env

            -   name: "Generate key"
                run: php artisan key:generate

            -   name: "Run Pint"
                run: vendor/bin/pint --test --verbose

            -   name: "Run PHPUnit"
                run: vendor/bin/phpunit

            -   name: "Run PHPStan"
                run: vendor/bin/phpstan --memory-limit=-1
